### ISSUE TITLE
请问是京东的前端开发团队维护的吗？

### ISSUE THREAD

**Issue by wlx200510** [JDsecretFE/quist-ui#1]
后续有无更多组件的计划？
关于对话框，我自己也开发了一个类似的组件，在使用时支持了如下特性：
部分页面需要展示顶部信号/电量那一栏，黑色蒙层是无法覆盖这部分内容的，导致样式很怪异
解决方法是传入两个color参数，当展示对话框时，顶部那部分的颜色设置为参数的
然后整体一致性得到保证

**Comment by secretFED** [comment]
后续会增加一些组件，也会对整个组件库的样式风格进行统一。很需要你这样的开发者给我们反馈问题，我们也会持续的升级优化。感谢
